CREATE TABLE IF NOT EXISTS top_crypto_details(
    SYSTEM_INSERTED_TIMESTAMP TIMESTAMP NOT NULL,
    RANK INT NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    SYMBOL VARCHAR(10) NOT NULL,
    PRICE DECIMAL(36,8) not null,
    PERCENT_CHANGE_24H DECIMAL(10,8) not null,
    VOLUME_24H DECIMAL(36,8) not null,
    MARKET_CAP DECIMAL(36,8) not null,
    CURRENCY VARCHAR(6) NOT NULL
);
